const assert = require('node:assert/strict');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const {chromium} = require('C:/Users/tlam/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');

(async () => {
  const browser = await chromium.launch({channel: 'msedge', headless: true});
  const page = await browser.newPage({viewport: {width: 1440, height: 1100}});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const url = pathToFileURL(path.join(__dirname, 'index.html')).href;
  const mainCard = id => page.locator(`#main-styles .card[data-id="${id}"]`);
  const excludedCard = id => page.locator(`#excluded-styles .card[data-id="${id}"]`);
  await page.goto(url);
  assert.equal(await page.locator('#main-styles .card').count(), 53);
  assert.equal(await page.locator('.card .favorite').count(), 53);
  assert.equal(await page.locator('.card .not-for-me').count(), 53);
  await mainCard('01').locator('.favorite').click();
  assert.equal(await mainCard('01').locator('.favorite').getAttribute('aria-pressed'), 'true');
  assert.equal(page.url(), url, 'Card button must not navigate');
  await mainCard('01').locator('.not-for-me').click();
  assert.equal(await mainCard('01').count(), 0);
  assert.equal(await excludedCard('01').count(), 1);
  assert.equal(await excludedCard('01').locator('.favorite').getAttribute('aria-pressed'), 'false');
  await page.reload();
  assert.equal(await excludedCard('01').count(), 1, 'Exclusion persists on reload');
  await excludedCard('01').locator('.card-link').click();
  assert.equal(await page.locator('.not-for-me').textContent(), 'Restore to main list');
  await page.locator('.favorite').click();
  assert.equal(await page.locator('.favorite').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('.not-for-me').getAttribute('aria-pressed'), 'false');
  await page.locator('header a').last().click();
  assert.equal(await mainCard('01').locator('.favorite').getAttribute('aria-pressed'), 'true');
  await mainCard('02').locator('.card-link').click();
  await page.locator('.not-for-me').click();
  await page.goBack();
  assert.equal(await excludedCard('02').count(), 1, 'Back navigation refreshes preferences');
  await page.locator('#shortlist').click();
  assert.equal(await page.locator('#main-styles .card:visible').count(), 1);
  assert.equal(await excludedCard('02').isVisible(), true, 'Excluded section remains available in shortlist mode');
  await excludedCard('02').locator('.not-for-me').click();
  assert.equal(await mainCard('02').count(), 1);
  assert.equal(await mainCard('02').isVisible(), false, 'Restoring does not automatically shortlist');
  await page.locator('#shortlist').click();
  await mainCard('51').locator('.not-for-me').click();
  await page.locator('[data-filter="jazz"]').click();
  assert.equal(await page.locator('#main-styles .card:visible').count(), 2);
  assert.equal(await page.locator('#excluded-styles .card:visible').count(), 1);
  await page.locator('#search').fill('Blue Hour');
  assert.equal(await page.locator('#main-styles .card:visible').count(), 1);
  assert.equal(await page.locator('#excluded-styles .card:visible').count(), 0);
  assert.match(await page.locator('#excluded-empty').textContent(), /No excluded styles match/);
  await page.locator('#search').fill('');
  await page.locator('[data-filter="all"]').click();
  await page.setViewportSize({width: 390, height: 844});
  await excludedCard('51').scrollIntoViewIfNeeded();
  await page.screenshot({path: path.join(__dirname, 'review', 'preferences-mobile.png')});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await excludedCard('51').locator('.favorite').click();
  assert.equal(await mainCard('51').locator('.favorite').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('#excluded-styles .card').count(), 0);
  const ids = await page.locator('#main-styles .card').evaluateAll(cards => cards.map(c => Number(c.dataset.id)));
  assert.deepEqual(ids, [...ids].sort((a, b) => a - b), 'Restored styles retain collection order');
  await page.setViewportSize({width: 1440, height: 1100});
  await mainCard('01').locator('.not-for-me').click();
  await page.locator('#not-for-me').scrollIntoViewIfNeeded();
  await page.screenshot({path: path.join(__dirname, 'review', 'preferences-desktop.png')});
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('Main/style buttons, persistence across pages/reload/back, exclusion/restoration, shortlist conflicts, search/collection filters, original order and mobile layout passed');
})().catch(error => {console.error(error); process.exit(1);});
