
const dialog=document.querySelector('dialog');
document.querySelectorAll('[data-enlarge]').forEach(b=>b.addEventListener('click',()=>{dialog.querySelector('img').src=b.dataset.enlarge;dialog.querySelector('img').alt=b.dataset.caption||'';dialog.showModal()}));
dialog?.querySelector('button').addEventListener('click',()=>dialog.close());
dialog?.addEventListener('click',ev=>{if(ev.target===dialog)dialog.close()});
let active=0,original=false;
const dataEl=document.querySelector('#view-data');
if(dataEl){const views=JSON.parse(dataEl.textContent),area=document.querySelector('.viewer'),label=document.querySelector('#view-label'),toggle=document.querySelector('.toggle'),zoom=document.querySelector('.zoom');
function paint(){const v=views[active],src=original?v.original:v.image;area.replaceChildren();if(src){const im=document.createElement('img');im.src=src;im.alt=(original?'Empty reference: ':'Style concept: ')+v.label;area.append(im)}else{const d=document.createElement('div');d.className='empty';d.textContent='This condo view is awaiting generation.';area.append(d)}label.textContent=(original?'Empty condo reference · ':'Furnished concept · ')+v.label;toggle.textContent=original?'Show styled view':'Show empty reference';toggle.setAttribute('aria-pressed',String(original));zoom.disabled=!src;document.querySelectorAll('[data-view]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===active)))}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{active=Number(b.dataset.view);paint()}));toggle.addEventListener('click',()=>{original=!original;paint()});zoom.addEventListener('click',()=>{const v=views[active];dialog.querySelector('img').src=original?v.original:v.image;dialog.querySelector('img').alt=v.label;dialog.showModal()});paint()}
const favorite=document.querySelector('.favorite');if(favorite){let set=[];try{set=JSON.parse(localStorage.getItem('condo-style-favorites')||'[]')}catch{};function paintFav(){const on=set.includes(favorite.dataset.id);favorite.setAttribute('aria-pressed',String(on));favorite.textContent=on?'Saved to shortlist':'Save to shortlist'}favorite.addEventListener('click',()=>{const id=favorite.dataset.id;set=set.includes(id)?set.filter(x=>x!==id):[...set,id];try{localStorage.setItem('condo-style-favorites',JSON.stringify(set))}catch{}paintFav()});paintFav()}
const search=document.querySelector('#search');if(search){let only=false;const cards=[...document.querySelectorAll('.card')];function filter(){let saved=[];try{saved=JSON.parse(localStorage.getItem('condo-style-favorites')||'[]')}catch{};const q=search.value.toLowerCase();let count=0;cards.forEach(c=>{const show=c.dataset.search.includes(q)&&(!only||saved.includes(c.dataset.id));c.hidden=!show;if(show)count++});document.querySelector('#result-count').textContent=count+' styles shown'}search.addEventListener('input',filter);document.querySelector('#shortlist').addEventListener('click',e=>{only=!only;e.target.textContent=only?'Show all styles':'Show my shortlist';e.target.setAttribute('aria-pressed',String(only));filter()});filter()}
